<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DotnetVersion)</TargetFramework>
        <RootNamespace/>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Testcontainers.MongoDb"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\core\Allegory.Axiom.TestBase\Allegory.Axiom.TestBase.csproj"/>
        <ProjectReference Include="..\..\..\src\ef-core\Allegory.Axiom.EntityFrameworkCore.MongoDB\Allegory.Axiom.EntityFrameworkCore.MongoDB.csproj"/>
    </ItemGroup>

</Project>
