<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DotnetVersion)</TargetFramework>
        <RootNamespace/>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\caching\Allegory.Axiom.Caching.Abstractions\Allegory.Axiom.Caching.Abstractions.csproj"/>
        <ProjectReference Include="..\..\data\Allegory.Axiom.Data.Abstractions\Allegory.Axiom.Data.Abstractions.csproj"/>
        <ProjectReference Include="..\..\event-bus\Allegory.Axiom.EventBus.Abstractions\Allegory.Axiom.EventBus.Abstractions.csproj"/>
        <ProjectReference Include="..\..\modularity\Allegory.Axiom.Hosting.Abstractions\Allegory.Axiom.Hosting.Abstractions.csproj"/>
        <ProjectReference Include="..\..\multi-tenancy\Allegory.Axiom.MultiTenancy.Abstractions\Allegory.Axiom.MultiTenancy.Abstractions.csproj"/>
        <ProjectReference Include="..\..\security\Allegory.Axiom.Security.Abstractions\Allegory.Axiom.Security.Abstractions.csproj"/>
        <ProjectReference Include="..\..\unit-of-work\Allegory.Axiom.UnitOfWork.Abstractions\Allegory.Axiom.UnitOfWork.Abstractions.csproj"/>
    </ItemGroup>

</Project>
