<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DotnetVersion)</TargetFramework>
        <RootNamespace/>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DistributedLock"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Allegory.Axiom.DistributedLocking\Allegory.Axiom.DistributedLocking.csproj"/>
        <ProjectReference Include="..\..\integration\Allegory.Axiom.Redis\Allegory.Axiom.Redis.csproj"/>
    </ItemGroup>

</Project>
