<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DotnetVersion)</TargetFramework>
        <RootNamespace/>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Allegory.Axiom.Assembly1\Allegory.Axiom.Assembly1.csproj"/>
    </ItemGroup>
</Project>
