packages:
  - 'apps/*'
  - 'libs/*'

allowBuilds:
  '@swc/core': true
  esbuild: true
  nx: true

catalog:
  nx: ~23.1.0
  '@nx/js': ~23.1.0
  '@nx/workspace': ~23.1.0
  '@nx/vite': ~23.1.0
  '@nx/vitest': ~23.1.0
  '@nx/web': ~23.1.0
  '@nx/react': ~23.1.0

  react: ^19
  react-dom: ^19
  react-router: ^7
  '@react-router/node': ^7
  '@react-router/serve': ^7
  '@react-router/dev': ^7
  zustand: ~5.0.0
  openid-client: ~6.8.0

  tailwindcss: ~4.3.0
  '@tailwindcss/vite': ~4.3.0
  shadcn: ~4.13.0
  radix-ui: ~1.5.0
  '@base-ui/react': ~1.6.0
  lucide-react: ~1.17.0
  clsx: ~2.1.0

  vite: ^8
  vitest: ~4.1.0
  vite-plugin-dts: ~4.5.0
  vite-plugin-static-copy: ~4.1.0
  '@vitejs/plugin-react': ^6
  '@testing-library/react': ~16.3.0
  '@testing-library/jest-dom': ~7.0.0
  jsdom: ~30.0.0

  prettier: ~3.6.0
  tslib: ^2

  '@types/node': ^20
  '@types/react': ^19
  '@types/react-dom': ^19

  typescript: ~5.9.0
  json-server: ~0.17.0
