<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DotnetVersion)</TargetFramework>
        <RootNamespace/>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Allegory.Axiom.UnitOfWork"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\core\Allegory.Axiom.Core\Allegory.Axiom.Core.csproj"/>
    </ItemGroup>

</Project>
