<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DotnetVersion)</TargetFramework>
        <RootNamespace/>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\data\Allegory.Axiom.Data.Abstractions\Allegory.Axiom.Data.Abstractions.csproj"/>
        <ProjectReference Include="..\..\ddd\Allegory.Axiom.Ddd.Domain\Allegory.Axiom.Ddd.Domain.csproj"/>
        <ProjectReference Include="..\..\modularity\Allegory.Axiom.Hosting.Abstractions\Allegory.Axiom.Hosting.Abstractions.csproj"/>
        <ProjectReference Include="..\..\multi-tenancy\Allegory.Axiom.MultiTenancy.Abstractions\Allegory.Axiom.MultiTenancy.Abstractions.csproj"/>
        <ProjectReference Include="..\..\unit-of-work\Allegory.Axiom.UnitOfWork.Abstractions\Allegory.Axiom.UnitOfWork.Abstractions.csproj"/>
    </ItemGroup>

</Project>
