name: Build and Test
on:

  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-and-test.yml'
      - 'framework/**'
      - 'modules/**'
      - 'Directory.*.props'

  pull_request:
    paths:
      - '.github/workflows/build-and-test.yml'
      - 'framework/**'
      - 'modules/**'
      - 'Directory.*.props'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Build
        run: ./etc/scripts/build.ps1
        shell: pwsh

      - name: Test
        run: ./etc/scripts/test.ps1 -Coverage
        shell: pwsh

      - name: Code Coverage Report
        uses: clearlyip/code-coverage-report-action@v7
        if: always()
        id: coverage
        with:
          filename: '${{ github.workspace }}/TestResults/coverage.cobertura.xml'
          badge: true
          # fail_on_negative_difference: true
          # overall_coverage_fail_threshold: 70
          artifact_download_workflow_names: 'build-and-test'